module.exports = {
  apps: [
    {
      name: "frontend",
      cwd: "/opt/next-app/current",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--max-old-space-size=1024",
        PORT: "3000",
        ENV_FILE: "/opt/next-app/shared/.env.production",
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "800M",
      max_restarts: 10,
      restart_delay: 2000,
      merge_logs: true,
      out_file: "/opt/next-app/shared/logs/frontend.out.log",
      error_file: "/opt/next-app/shared/logs/frontend.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "nodeApp",
      cwd: "/opt/next-app/current",
      script: "./nodeApp.mjs",
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--max-old-space-size=1024",
        ENV_FILE: "/opt/next-app/shared/.env.production",
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "800M",
      max_restarts: 10,
      restart_delay: 2000,
      exp_backoff_restart_delay: 2000,
      merge_logs: true,
      out_file: "/opt/next-app/shared/logs/nodeApp.out.log",
      error_file: "/opt/next-app/shared/logs/nodeApp.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "nodeBatch",
      cwd: "/opt/next-app/current",
      script: "./nodeBatch.mjs",
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--max-old-space-size=1024",
        ENV_FILE: "/opt/next-app/shared/.env.production",
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "800M",
      max_restarts: 10,
      restart_delay: 2000,
      exp_backoff_restart_delay: 2000,
      merge_logs: true,
      out_file: "/opt/next-app/shared/logs/nodeBatch.out.log",
      error_file: "/opt/next-app/shared/logs/nodeBatch.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "nodeLive",
      cwd: "/opt/next-app/current",
      script: "./nodeLive.mjs",
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--max-old-space-size=1024",
        ENV_FILE: "/opt/next-app/shared/.env.production",
      },
      watch: false,
      autorestart: true,
      max_memory_restart: "500M",
      max_restarts: 10,
      restart_delay: 2000,
      exp_backoff_restart_delay: 2000,
      merge_logs: true,
      out_file: "/opt/next-app/shared/logs/nodeLive.out.log",
      error_file: "/opt/next-app/shared/logs/nodeLive.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
