export const texts = {
  menu: {
    adminLoginTitle: "管理者ログイン",
    adminDashboard: "ダッシュボード",
    memberLoginTitle: "ログイン",
    forgotPassword: "パスワードを忘れた方",
    reissuePassword: "パスワード再発行",
    changePassword: "パスワード変更",
    adminMemberTitle: "会員管理",
    adminMemberRegist: "会員登録",
    adminMemberList: "会員一覧",
    adminTorihikiJisseki: "取引実績",
    adminTorihikiJissekiMeisai: "取引実績明細",
    adminMemberAddinfoItemRegist: "会員項目追加設定",
    adminStaffTitle: "スタッフ管理",
    adminStaffRegist: "スタッフ登録",
    adminStaffList: "スタッフ一覧",
    adminKengenRegist: "権限管理",
    adminGoodsTitle: "商品管理",
    adminGoodsList: "商品一覧",
    adminGoodsRegist: "商品登録",
    adminGoodsBulkRegist: "商品一括登録",
    adminBidList: "入札一覧",
    adminBidLogList: "入札ログ",
    adminAuctionner: "オークショニア",
    adminAuctionner_1: "オークショニア(オンライン+会場)",
    adminAuctionner_2: "オークショニア(オンラインのみ)",
    adminGoodsAddinfoItemRegist: "商品項目追加設定",
    adminCategoryRegist: "カテゴリー管理",
    adminAuctionTitle: "オークション管理",
    adminKaisaiRegist: "開催回管理",
    adminLiveTitle: "ライブ管理",
    adminLiveBidUnitRegist: "ライブ入札単位管理",
    adminLiveMessageRegist: "ライブメッセージ管理",
    adminPaddleManagement: "パドル管理",
    adminLiveScreen: "会場スクリーン",
    adminInfoRegist: "お知らせ管理",
    adminTopImageRegist: "TOP画像管理",
    adminSettingTitle: "設定管理",
    adminSystemRegist: "システム設定",
    adminAdminRegist: "管理者情報",
    adminMailRegist: "メールテンプレート設定",
    adminPageSetting: "静的ページ設定",
    memberSignup: "新規会員登録",
    memberSignupCompletion: "会員登録完了",
    memberContact: "お問い合わせ",
    memberContactCompletion: "お問い合わせ完了",
    memberGoodsList: "商品一覧",
    memberGoodsDetail: "商品詳細",
    memberTop: "TOP",
    memberAuction: "スケジュール",
    memberJoinLive: "ライブに参加する",
    memberMyPage: "マイページ",
    memberRakusatsu: "落札一覧",
    memberInvoice: "請求一覧",
    memberAccount: "会員登録情報",
    memberLive: "ライブ入札",
    loginCertification: "本登録",
  },
  button: {
    logout: "ログアウト",
    search: "検索",
    shoninOn: "承認する",
    shoninOff: "未承認に戻す",
    teishiOn: "停止する",
    teishiOff: "利用中に戻す",
    regist: "登録",
    update: "更新",
    goodsInfoRegist: "商品情報登録",
    goodsKekkaRegist: "落札結果登録",
    backFurakusatsu: "不落札に戻す",
    staffRegist: "スタッフ情報登録",
    delete: "削除",
    csv: "CSV出力",
    invoicePdf: "請求書出力",
    torihikiCsv: "取引CSV出力",
    torihikiMeisaiCsv: "取引明細CSV出力",
    addressCopy: "メールアドレスコピー",
    csvForAdminGoodsRegist: "商品一括取込用CSV出力",
    csvForTesuryo: "落札手数料取込用CSV出力",
    login: "ログイン",
    send: "送信",
    sendConfirm: "送信内容を確認する",
    reset: "リセット",
    cancel: "キャンセル",
    shimeOn: "締め処理",
    shimeOff: "締め解除",
    newSignup: "新規会員登録",
    memberRegist: "会員情報更新",
    backLogin: "ログイン画面に戻る",
    upload: "アップロード",
    clear: "クリア",
    systemSettingRegist: "システム設定登録",
    faviconImageRegist: "ファビコン画像登録",
    faviconImageDelete: "ファビコン画像削除",
    logoImageRegist: "アイコン画像登録",
    logoImageDelete: "アイコン画像削除",
    riyoKiyakuRegist: "利用規約登録",
    riyoKiyakuDelete: "利用規約削除",
    privacyPolicyRegist: "プライバシーポリシー登録",
    privacyPolicyDelete: "プライバシーポリシー削除",
    detail: "詳しく見る",
    toGoodsList: "出品一覧を確認する",
    liveApplication: "ライブ参加申込",
    bidToggle: "入札する",
    bidConfirm: "入札確認",
    bidConfirmed: "入札確定",
    jizenBidToggle: "事前入札する",
    deleteJizenBidToggle: "事前入札を削除する",
    onlineBidshoninOn: "オンライン入札承認",
    call: "呼び出し",
    beforeLot: "前LOT(←)",
    affterLot: "次LOT(→)",
    set: "セット(F3)",
    start: "スタート(F4)",
    liveClear: "強制クリア",
    minusSerihaba: "-セリ幅(↓)",
    plusSerihaba: "+セリ幅(↑)",
    currentPrice: "現在価格を配信(enter)",
    onlinePrice: "オンライン入札価格を配信(shift)",
    BidComingSoon: "もうすぐ落札",
    BidFinush: "入札終了",
    furakusatsu: "不落札(F1)",
    rakusatsu: "落札(F9)",
    close: "閉じる",
    updateSerikekka: "セリ結果登録(F9)",
    rakusatsuProcess: "落札処理(F8)",
    bidRestart: "入札再開(F8)",
    haishin: "配信",
    memberSearchModal: "会員検索",
    invoice: "請求書出力",
  },
  fileName: {
    memberCsv: "会員一覧",
    goodsCsv: "商品一覧",
    goodsCsvForAdminGoodsRegist: "商品一覧(商品一括取込用)",
    bidCsv: "入札一覧",
    bidLogCsv: "入札ログ",
  },
  login: {
    userName: "Username",
    password: "パスワード",
    forgotPassword: "パスワードを忘れた方",
    registMail: "登録メールアドレス",
    newPassword: "新しいパスワード",
    newPasswordConfirm: "新しいパスワード（確認用）",
    newCustomer: "新しいお客様",
  },
  chanePassword: {
    oldPassword: "現在のパスワード",
  },
  loginCertification: {
    oldPassword: "初回パスワード",
  },
  member: {
    userId: "会員ID",
    loginId: "ログインID",
    userName: "ユーザー名",
    userNameKana: "ユーザー名(カナ)",
    companyName: "会社名",
    companyNameKana: "会社名(カナ)",
    companyUrl: "会社URL",
    zipCode: "郵便番号",
    todofuken: "都道府県",
    address1: "市区町村",
    address2: "番地以下",
    tel: "電話番号",
    fax: "FAX番号",
    mobile: "携帯番号",
    shonin: "承認",
    shoninOff: "未承認",
    shoninOn: "承認済",
    address: "住所",
    adminBiko: "管理者用備考",
    kiyaku: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    consent: "に同意する",
    shonin_note_1: "※承認する：会員様にログインに必要なログインID,パスワードがメール送信されます。",
    shonin_note_2:
      "※未承認に戻す：ログイン不可になります。会員様がパスワードを紛失されたなど、再発行が必要時に使用してください。",
    mailcopy: "メールアドレスコピー",
    mailcopy_note:
      "※メールアドレスコピー：メールアドレスをコピーしてGmail等メーラーのBCCに貼り付ければ、一括送信が可能です",
    auctionMailJushinFlg: "お知らせメール受信",
  },
  staff: {
    info: "スタッフ情報",
    staffId: "スタッフID",
    loginId: "ログインID",
    password: "パスワード",
    staffName: "スタッフ名",
    kengenId: "権限ID",
    kengenName: "権限名",
  },
  topImage: {
    topImage_note_2: "※推奨サイズ：横1920×縦1080 16:9の画像比率が推奨です。",
  },
  goods: {
    info: "商品管理情報",
    thumbnailImageUrl: "画像",
    goodsId: "商品ID",
    goodsName: "商品名",
    category: "カテゴリー",
    lot: "LOT",
    lotFrom: "LOT FROM",
    lotTo: "LOT TO",
    auctionName: "開催名",
    keisaiFlg: "掲載状況",
    kekkaStatus: "結果ステータス",
    startPrice: "スタート価格",
    currentPrice: "現在価格",
    saiteiRakusatsuPrice: "最低落札価格",
    saiteiRakusatsuPrice_note_1: "設定しない場合は空白で登録",
    rakusatsuPrice: "落札金額",
    rakusatsuTesuryoPrice: "落札手数料金額",
    kekkaRegisttime: "落札結果登録日時",
    shuppinUserId: "出品ユーザーID",
    shuppinUserId_note_1: "自社出品時は空白で登録",
    shuppinUserName: "出品ユーザー名",
    shuppinCompanyName: "出品会社名",
    rakusatsuUserId: "落札ユーザーID",
    rakusatsuUserName: "落札ユーザー名",
    rakusatsuCompanyName: "落札会社名",
    currentUserId: "最高額入札ユーザーID",
    currentUserName: "最高額入札ユーザー名",
    currentCompanyName: "最高額入札会社名",
    sku: "自社管理番号",
    SKU: "SKU",
    goodsSetsumei: "商品説明",
    goodsSetsumei_note1: "※縦に４行まで表示されます",
    biko: "備考",
    biko_note1: "※商品詳細画面に表示されます",
    adminBiko: "管理者用備考",
    chumokuFlg: "注目",
    hikeisaiFlg: "掲載",
    bidUnit: "入札幅",
    bidCount: "入札数",
    favoriteCount: "お気に入り数",
    goodsInfo: "商品情報",
    tesuryoUpdate: "落札手数料更新",
    goodsImage: "商品画像",
    shiyosho: "仕様書",
    info2: "フォルダzip>商品番号フォルダorSKU>画像",
    info3: "ZIP形式画像フォルダ",
    uploading: "アップロード中...",
    image_torikomi_time: "取込日時",
    image_torikomi_all: "全件",
    image_torikomi_notorikomi: "未登録",
    image_torikomi_oktorikomi: "登録済",
    image_torikomi_eroortorikomi: "エラー",
    image_torikomi_shosaitorikomi: "明細",
    image_torikomi_status: "ステータス",
    image_torikomi_foldername: "フォルダ名",
    image_torikomi_message: "メッセージ",
    button_tab1: "一括ファイル取込",
    button_tab2: "一括再出品登録",
    relist_button: "チェックした作品を一括再出品登録",
    relist_auction: "再出品開催回",
    kensakujoken: "※流れ作品のみ一覧に表示されます",
    csv_info2: "CSV形式ファイル",
    image_note_1: "※一枚目の画像が商品一覧に表示されます。",
    image_note_2: "※登録可能なファイル形式は'jpg', 'jpeg', 'png'です。",
    goods_note_1: "締め済みのため、登録ボタン・削除ボタンは非表示になります。",
    goods_note_2: "入札済みのため、オークションに関する項目は変更不可となります。",
    goods_search_1: "自分が入札した商品",
    goods_search_2: "お気に入り登録した商品",
    goods_search_3: "注目商品",
    goods_search_4: "終了していない商品",
    bidPrice: "入札金額",
    jizenBidPrice: "事前入札金額",
    RemainingTime: "残り時間",
    auctionStatus1: "落札",
    auctionStatus2: "終了",
    auctionStatus3: "最高額入札者",
    auctionStatus4: "最高額更新",
    auctionStatus5: "最低落札価格に達していません",
    sort_lot_asc: "LOT昇順",
    sort_lot_desc: "LOT降順",
    sort_price_asc: "現在価格が安い順",
    sort_price_desc: "現在価格が高い順",
    estimate: "エスティメイト",
    farst_jizen_nyusatsu: "最高事前入札者",
    second_jizen_nyusatsu: "2番目事前入札者",
    goodsRegistStatus: "画像登録状況",
    registDatetime: "登録日時",
    registFolderName: "フォルダ名",
    registStatus: "登録状況",
    mishori: "未処理",
    shorichu: "処理中",
    shorizumi: "処理済み",
    error: "エラー",
    goodsUpload_note_1: "CSVファイルを選択してください、その他の形式はアップロードできません。",
    goodsUpload_note_2:
      "ZIP形式の画像フォルダを選択してください、その他の形式画像はアップロードできません。",
    goodsUpload_note_3: "ZIPファイルサイズは2.0GB以下にしてください。",
    goodsUpload_note_4: "※登録後、30日以内で登録済みでないフォルダが表示されます。",
    goodsUpload_note_5: "※30日経過して商品に紐づかない画像は削除されます。",
    goodsUpload_note_6:
      "CSVファイル内のデータは、項目ごとにダブルクォーテーション「””」で囲ってください。",
    goodsUpload_note_7:
      "CSVファイルのアップロード後、ファイル内データのチェック処理を実行します。登録できないデータがある場合はエラーメッセージに表示されます。",
    goodsUpload_note_8: "すべてのデータについてチェックが通った場合のみ登録されます。",
    goodsUpload_note_9: "画像登録スケジュール",
    goodsUpload_note_10: "毎時10分、30分、50分：100商品ごとに画像と商品を紐づけて登録",
    goodsUpload_note_11: "毎時15分、45分：ZIPファイルの解凍",
  },
  auction: {
    spnKbn: "出品区分",
    auctionCount: "開催回",
    auctionName: "開催名",
    auctionDate: "開催日",
    displayKikan: "掲載期間",
    displayKikan_note_1:
      "※終了５分前の入札から入札期間が自動延長しますが、掲載期間を過ぎると非表示となります。掲載期間は余裕をもって登録してください。",
    bidKikan: "入札期間",
    shomenbidKikan: "書面入札期間",
    onlinebidApplicationKikan: "オンライン入札申請期間",
    auctionGaiyo: "概要",
    auctionGaiyoPreview: "概要プレビュー",
    auctionImage: "オークションメイン画像",
    auctionImage_note_1: "※登録可能なファイル形式は'jpg', 'jpeg', 'png'です。",
    auctionImage_note_2: "※推奨サイズ：横1920×縦1080 16:9の画像比率が推奨です。",
    goodsListUrl: "商品リスト",
    goodsListUrl_note_1: "※登録可能なファイル形式は'pdf', 'xlsx'です。",
    goodsListUrl_note_2: "※登録すると、会員様が商品一覧よりダウンロード可能となります",
    shime: "オークション締め",
    shime_note_1: "※締め処理を行うと、登録された商品情報が変更不可になります。",
    auctionGaiyoOpen: "開催概要を確認する+",
    auctionGaiyoClose: "開催概要を閉じる×",
    kaisaiYotei: "開催予定",
    auction: "オークション",
    spnKbn1: "ライブオークション",
    spnKbn2: "ライブオークション",
    spnKbn3: "インターネットオークション",
    spnKbn4: "非公開形式オークション",
    kaisaiStatus1: "開催予定",
    kaisaiStatus2: "開催中",
    kaisaiStatus3: "終了",
    GoodsListLabel: "商品リストを確認する",
    paymentDeadlineDate: "支払期限",
  },
  signup: {
    signup_note_1: "管理者側にて、承認後ログイン情報が登録されたメールに送信されます。",
    signup_note_2: "ログイン情報が登録されたメールに送信されました。",
  },
  contact: {
    name: "お名前",
    nameKana: "お名前(カナ)",
    tel: "連絡先",
    title: "件名",
    text: "お問い合わせ内容",
    confirm: "入力内容の確認",
    confirm_note_1: "入力された内容で送信します。",
    confirm_complete_note_1:
      "担当者に送信されました。入力されたメールアドレス宛に受付メールが送信されています。",
  },
  bid: {
    auctionSeq: "開催回",
    bidPrice: "入札額",
    bidTime: "入札日時",
  },
  paddle: {
    paddleKbn: "パドル区分",
    paddleNo: "パドル番号",
    paddleKbn_note_1: "※オンラインで登録すると、会員にメール送信されます。",
    onlineBidshonin: "オンライン入札承認",
    onlineBidshonin_note_1: "※承認すると、会員にメール送信されます。",
    shoninzumi: "承認済み",
    liveApplication: "ライブ入札申請済み",
  },
  admin: {
    companyUrl: "企業情報URL",
    kobutsuBango: "古物商番号",
    copyRight: "コピーライト",
    invoiceNo: "インボイス登録番号",
    furikomiKozaName: "振込先口座名",
    furikomiGinkoName: "振込先銀行名",
    furikomiShitenName: "振込先支店名",
    furikomiKozaShurui: "振込先口座種類",
    furikomiKozaNo: "振込先口座番号",
    admin_note_1: "※会員側のフッターに表示されます",
    admin_note_2: "※会員側のフッターの企業情報のリンク先になります",
    admin_note_3: "※システムメールの管理者側の受信先になります",
    admin_note_4: "※請求書に表示されます",
  },
  system: {
    memberRegistration: "会員登録設定",
    memberApproval: "会員承認設定",
    nologinView: "ログイン参照設定",
    youtubeLink: "Youtubeリンク",
    adminOnly: "管理者のみ",
    adminAndMember: "管理者・会員",
    approve: "承認する",
    reject: "承認しない",
    loginedOnly: "ログイン者のみ",
    allMember: "全会員",
    allow: "許可する",
    deny: "許可しない",
    faviconImage: "ファビコン画像",
    logoImage: "アイコン画像",
    riyoKiyaku: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    zipCodeUpload: "郵便番号データアップロード",
    systemRegist_note_1: "※管理者のみ：会員側の画面で新規会員登録画面が非表示となります。",
    systemRegist_note_2:
      "※承認する：会員側で新規会員登録があった場合、管理者側で承認作業をしたのちにログイン情報がメール送信されます。",
    systemRegist_note_3:
      "※承認しない：会員側で新規会員登録があった場合、即時ログイン情報がメール送信されます。",
    systemRegist_note_4:
      "※ログイン者のみ：ログインしていない場合、TOP・スケジュール・商品一覧・商品詳細画面が表示されません 。",
    systemRegist_note_5: "※許可する：会員側の商品詳細画面で画像ダウンロードが可能になります。",
    systemRegist_note_6: "※ファイル形式は.icoのみになります。",
    systemRegist_note_7: "※ファイル形式は.jpg、.pngのみになります。",
    systemRegist_note_8: "※ファイル形式は.pdfのみになります。",
    systemRegist_note_9: "※ファイル形式は.zipのみになります。",
    systemRegist_note_10:
      "※こちらのリンクからファイルをダウンロードして、アップロードしてください。",
  },
  addInfoItem: {
    item: "項目",
    item_note_1: "項目を削除する時は空で更新してください。",
    item_note_2:
      "一度設定した項目で会員情報を登録済みの場合、項目変更しても登録済みの内容は残ります。",
    item_note_3:
      "一度設定した項目で商品情報を登録済みの場合、項目変更しても登録済みの内容は残ります。",
  },
  mail: {
    shomei: "署名",
    mail_note_2: "※入力不可の箇所は、システムから自動生成になりますので編集不可となります。",
    templateName: "テンプレート名",
    templateSetsumei: "使用ケース",
    subject: "メールタイトル",
    bodyPart1: "メール本文①",
    bodyPart2: "メール本文②",
    bodyPart3: "メール本文③",
    bodyPart4: "メール本文④",
    body: "本文プレビュー",
  },
  category: {
    categoryName: "カテゴリー名",
  },
  kengen: {
    kengenName: "権限名",
    screenName: "画面名",
    hidden: "非表示",
    kengen: "権限",
    readOnly: "参照のみ",
    allowAll: "すべて許可",
    kengen_note_1: "※参照のみ：メニューに表示されます。検索表示のみ可能です。",
    kengen_note_2: "設定後、再ログインすると反映されます。",
  },
  live: {
    bid: "入札",
    bidStatus1: "最高額入札中",
    bidStatus2: "落札しました",
    bidStatus3: "他のユーザーが落札しました",
    bidStatus4: "不落札",
    bidStatus5: "最低落札価格に達していません",
    noLiveAuction1: "次回の開催予定は",
    noLiveAuction2: "です。",
    noLiveAuction3: "開催日当日になると、入札画面が開きます。",
  },
  info: {
    naiyo: "お知らせ内容",
    naiyoUrl: "テキストリンク",
    info: "掲載期間",
    delete: "削除",
    notice: "※データが削除され管理者側でも非表示になります。",
    note_1: "※登録した場合のみお知らせにテキストリンクが表示されます",
  },
  page: {
    name: "ページ名",
    url: "url",
    file: "PDFファイル添付",
    loginAll: "全員表示",
    loginOnly: "ログイン者のみ表示",
    note_1: "※設定すると会員側のメニュー表示されます",
    note_2: "※URLには外部リンク先を設定可能です。",
    note_3:
      "※PDFファイル添付すると、自動でURLが発行されます。添付した場合、PDF情報が優先してURL設定されます。",
    note_4: "※削除する場合は、各項目を空にして更新ボタンを押してください。",
  },
  torihikiJisseki: {
    shuppinsu: "出品数",
    shuppinPrice: "出品落札金額",
    shuppinTesuryoPrice: "出品手数料金額",
    shuppinTotalPrice: "出品合計支払金額",
    rakusatsusu: "落札数",
    rakusatsuPrice: "落札金額",
    rakusatsuTesuryoPrice: "落札手数料金額",
    rakusatsuTotalPrice: "落札合計請求金額",
    rakusatsuMeisai: "落札明細",
    shuppinMeisai: "出品明細",
    updateDate: "日付登録",
    nyukinbi: "入金日",
    hassobi: "発送日",
    shiharaibi: "支払日",
  },
  bidUnit: {
    unitRange: "現在価格範囲",
    bidUnit: "入札単位",
  },
  livemessage: {
    message: "メッセージ",
    confirmClear: "強制クリアします。よろしいですか？",
    updateSerikekka: "次のせり結果を登録します。よろしいですか？",
    updateSerikekkaData_1: "セリ結果：",
    updateSerikekkaData_2: "権利者：",
    updateSerikekkaData_3: "落札価格：",
    furakusatsu: "不落札",
    rakusatsu: "落札",
    rakusatsuProcessMsg: "落札処理中",
  },
  mypageResult: {
    rakusatsuTotalPrice: "落札合計金額",
  },
  top: {
    auction: "開催中のオークション",
    hotGoods: "注目商品",
  },
  common: {
    mail: "メールアドレス",
    freeWord: "フリーワード",
    tilde: "～",
    asterisk: "※",
    colon: "：",
    errorMsg: "エラーメッセージ",
    mailJushinOn: "受信する",
    mailJushinOff: "受信しない",
  },
  label: {
    require: "必須",
    goodsListMark: "商品一覧表示",
    resultKekka: "検索結果:",
    resultCount: "件",
    newRegist: "新規登録",
    teishi: "停止",
    teishi_note_1: "※停止：ログイン不可になります。",
    delete: "削除",
    delete_note_1: "※データが削除され,管理者側でも非表示になります。",
    forgotPassword_note_1:
      "パスワードを再設定するためのメールを送信しますので、お客様のメールアドレスをご記入ください。",
    forgotPassword_note_2: "登録されてないメールアドレスを入力された場合は、メール送信されません。",
    registPassword_note_1:
      "数字、記号、アルファベットを含めた8文字以上を半角文字で入力してください。",
    hankakuInput: "※半角数字で入力してください",
    imageUploadExtensionError: "※対応していないファイル形式です。",
    text_note_1: "※テキスト形式、HTML形式どちらでも入力可能です。",
    text_note_2: "※改行したいときは、改行コード<br/>を入力してください。",
    csvBtn_note_1: "検索結果を出力します。",
    csvForAdminGoodsRegistBtn_note_1: "商品一括アップロード画面に使用する情報を出力します。",
    select_note_1: "選択してください。",
    open_search_joken: "検索条件を開く",
    sort: "並び順",
    download: "ダウンロード",
    asc: "降順",
    desc: "昇順",
  },
  message: {
    redirect: "ログイン画面に遷移します。",
    regist: "登録完了しました。",
    delete: "削除完了しました。",
    shoninRegist: "承認完了しました。ログイン情報が会員にメール送信されました。",
    noShoninRegist: "承認解除しました。",
    selectAtLeastOne: "対象が選択されていません。",
    confirmDelete: "本当に削除してもよろしいですか？",
    confirmShime: "締め処理を行います。よろしいですか？",
    nologin: "ログインできません",
    forgotPassword: "登録されたメールアドレスにパスワード再発行のメールが送信されました。",
    changePassword: "パスワード変更が完了しました。",
    noResult: "検索結果がありません。",
    error400: "入力内容に誤りがあります。",
    registBid: "入札が完了しました。",
    highestBid: "落札権利を取得しました。",
    noHighestBid: "入札しましたが、落札権利を取得できませんでした。",
    isNextPriceBelow: "次価格が現在価格以下でセットされています。",
  },
  pulldown: {
    keisaiFlgOn: "掲載",
    keisaiFlgOff: "非掲載",
    furakusatsu: "不落札",
    rakusatsu: "落札",
  },
};
