export type TGoodsSearchRequest = {
  goodsId?: string;
  goodsName?: string;
  categorySeq?: string;
  auctionSeq?: string;
  lot?: string;
  startCurrentPriceFrom?: string;
  startCurrentPriceTo?: string;
  freeWord?: string;
  countFlg?: boolean;
  pageNumber: number;
  pageSize: number;
  sortKey?: string;
  sortFlg?: boolean;
};

export type TGoodsSelect = {
  thumbnailImageUrl: string;
  originalImageUrl: string;
  squareImageUrl: string;
  goodsId: number;
  goodsName: string;
  goodsSetsumei: string;
  categorySeq: number;
  categoryName: string;
  biko: string;
  chumokuFlg: boolean;
  spnKbn: string;
  auctionSeq: number;
  auctionName: string;
  shuppinUserId: string;
  lot: string;
  startPrice: string;
  currentKenriUserId: number;
  currentPrice: string;
  startCurrentPrice: string;
  bidCount: number;
  favoriteCount: number;
  rakusatsuPrice: string;
  addInfo1: string;
  addInfo2: string;
  addInfo3: string;
  addInfo4: string;
  addInfo5: string;
  addInfo6: string;
  addInfo7: string;
  addInfo8: string;
  addInfo9: string;
  addInfo10: string;
  auctionStatus: number;
  auctionTimeStatus: number;
  remainingTime: string;
  bidPrice: string;
  nextBidPrice: string;
  myFavoriteFlg: boolean;
  saiteiRakusatsuPriceOverFlg: boolean;
  [key: string]: any;
};

export type TGoodsBeforeAfterLot = {
  beforeGoodsId: number;
  afterGoodsId: number;
};
