import { Dayjs } from "dayjs";
export type TAdminUserRegistRequest = {
  userId?: number;
  loginId?: string;
  userName?: string;
  userNameKana?: string;
  companyName?: string;
  companyNameKana?: string;
  companyUrl?: string;
  zipCode?: string;
  todofukenName?: string;
  address1?: string;
  address2?: string;
  tel?: string;
  mobile?: string;
  fax?: string;
  mail?: string;
  auctionMailJushinFlg?: boolean;
  ginkoCode?: string;
  ginkoName?: string;
  shitenCode?: string;
  shitenName?: string;
  kozaType?: string;
  kozameigi?: string;
  kozabango?: string;
  adminBiko?: string;
  shoninFlg?: boolean;
  teishiFlg?: boolean;
  bidFlg?: boolean;
  loginTime?: Dayjs | null;
  updateTime?: Dayjs | null;
  createTime?: Dayjs | null;
};
